### ISSUE TITLE
French simple date format

### ISSUE THREAD

**Issue by Incognito-Nemo** [dalelotts/angular-date-time-input#10]
Hello!

You can see my problem on http://plnkr.co/edit/qB39hGTYKQXgE1vIHZJc?p=preview : when I put 25/01/2015 for exemple in the input, the result is not valid (2018-01-01T00:00:00+01:00).

What Am I missing ?

Thanks for you help !

J.-Luc

**Comment by dalelotts** [comment]
Actually, the result is valid in your example. A Date object (not a string) is stored in the model.

If you really want to store a string you can give the code in the develop branch a try.

**Comment by Incognito-Nemo** [comment]
sorry but when i modify the date in the input from 25 to 26 for example the date result is always not correct.

**Comment by dalelotts** [comment]
I updated the example you used to include the latest version of this directive - does this work correctly?

http://plnkr.co/edit/zcHljRCzRBE25HnY41GO?p=preview

**Comment by Incognito-Nemo** [comment]
yes when I delete , 'ui.bootstrap.datetimepicker' in var myApp = angular
  .module('myApp', ['ui.dateTimeInput'])
  .controller('dateTimePickerController', dateTimePickerController);

Thanks !
