### ISSUE TITLE
这个插件和angular filter date的区别

### ISSUE THREAD

**Issue by 275287902** [dalelotts/angular-date-time-input#15]
请问这个插件和angular filter date 有什么区别呢？谢谢。

**Comment by dalelotts** [comment]
用这个插件在文本框中输入日期。对不起，我的中国不好.

**Comment by dalelotts** [comment]
Angular filter date is used to display a date - this is used to enter a date.

**Comment by 275287902** [comment]
Thank you very much, I'm just on the way to work, suddenly want to see, but just the next test, the use of the know, my English is not good, I will try to learn English. Thank you for your reply to me so fast.
data-date-formats: This is used to accept the date format
date-time-input: This is the date format ng-module format (angular filter date is not formatted ng-module of);

java accept this format "YYYYMMDDHHmmss", view and also displayed as 'YYYY-MM-DD HH: mm: ss' format such
It can be used:
modelType: 'YYYYMMDDHHmmss'
data-date-formats: "YYYYMMDDHHmmss"
date-time-input: "YYYY-MM-DD HH: mm: ss"

Thank you for helping me!

**Comment by dalelotts** [comment]
没问题。 试
modelType: 'YYYYMMDDHHmmss'
data-date-formats: ["YYYYMMDDHHmmss",  "YYYY-MM-DD HH: mm: ss"]
date-time-input: "YYYY-MM-DD HH: mm: ss"
