### ISSUE TITLE
Displaying wrong date 

### ISSUE THREAD

**Issue by BramDecuypere** [dalelotts/angular-date-time-input#17]
Hi somehow something goes wrong with displaying the dates, the underlying values seem to be the correct date. It looks like every date after this double 30 30 is displayed wrong.

Any idea what the issue might be?

<img width="319" alt="screen shot 2016-06-17 at 09 39 20" src="https://cloud.githubusercontent.com/assets/7522178/16143904/19300ec6-3470-11e6-99fb-f90b3a8bed39.png">

**Comment by dalelotts** [comment]
I think maybe this issue is against the wrong project. Can you please create a fiddle showing the issue and open it against the correct project?

**Comment by dalelotts** [comment]
Also, just an FYI that I do not see this on the demo site so include your time zone.

**Comment by BramDecuypere** [comment]
Ok thanks for the fast response, I will create a fiddle right away.
