### ISSUE TITLE
missing a ; at the end

### ISSUE THREAD

**Issue by pdorgambide** [dalelotts/angular-date-time-input#26]
On combine with other libs  with gulp to deploy enviremoent:

> TypeError: (intermediate value)(intermediate value)(...) is not a function

>  DateTimeInputDirective.$inject = ['dateTimeParserFactory']

[http://stackoverflow.com/questions/20307462/js-cant-combine-lib-files](http://stackoverflow.com/questions/20307462/js-cant-combine-lib-files)

**Comment by dalelotts** [comment]
Duplicate of #23 

See https://github.com/dalelotts/angular-bootstrap-datetimepicker/issues/353 and https://github.com/dalelotts/angular-bootstrap-datetimepicker/issues/347 for more details on how to fix your build process to minifiy and concatenate without injecting defects.
