### ISSUE TITLE
Missing format when validating

### ISSUE THREAD

**Issue by freeboarder** [dalelotts/angular-date-time-input#3]
In validateFn moment is created without the format. That causes validation errors when using a certain format (like "L HH:mm:ss") at least in combination with localization (like German). If changing the displayed value in a valid way, the moment date is invalid.

Solution: Create the moment instance using the format:
var momentValue = moment(viewValue, attrs.dateTimeInput);

**Comment by dalelotts** [comment]
Sorry for the extreme delay. Can you verify that this is fixed in the develop branch?

**Comment by dalelotts** [comment]
Closing because I believe this is fixed now
