### ISSUE TITLE
This directive is not working on my production server.

### ISSUE THREAD

**Issue by TejasCMehta** [dalelotts/angular-date-time-input#5]
First of all good work!!

I used this directive along with angular-bootstrap-datetimepicker directive in my project. This all works well in dev environment but not on production server.

Dropdown dateTime picker opens calender but after selecting datetime, format directive is not working. It shows date in inputbox in below format.
`Thu Nov 13 2014 10:00:00 GMT+0530 (India Standard Time)`

Any help??
Thanks.

**Comment by dalelotts** [comment]
Closing because of lack of response from OP.
