### ISSUE TITLE
[Question] Is it necessary to bind blur event on input 

### ISSUE THREAD

**Issue by hungdoan2** [dalelotts/angular-date-time-input#8]
Is it necessary to bind blur event on input ?

    element.bind('blur', function () {
            var viewValue = controller.$modelValue;
            angular.forEach(controller.$formatters, function (formatter) {
              viewValue = formatter(viewValue);
            });
            controller.$viewValue = viewValue;
            controller.$render();
          });

Because:
controller.$parsers.unshift(validateFn);
controller.$formatters.push(formatFn);

Is called automatically when model or view is changed.

**Comment by dalelotts** [comment]
It's been a while since I worked on this, and I don't have tests in place to help me remember the implementation details, but my guess is that at the time (1.0, 1.1 era angular) it was required - it may no longer be required. 

If you remove it, does it work correctly?

**Comment by dalelotts** [comment]
Sorry for the extreme delay. I tested recently, and binding to blur is required.
